# Generated by Django 5.0.6 on 2024-05-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JossaCollegeBranchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollegeID', models.IntegerField()),
                ('BranchName', models.CharField(max_length=100)),
                ('BranchOpeningRank', models.CharField(max_length=100)),
                ('BranchClosingRank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JossaCollegeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollegeID', models.IntegerField()),
                ('CollegeName', models.CharField(max_length=100)),
                ('CollegeDescription', models.CharField(max_length=500)),
                ('OpeningRank', models.CharField(max_length=10)),
                ('ClosingRank', models.CharField(max_length=10)),
                ('HeighestPackage', models.CharField(max_length=20)),
                ('AveragePackage', models.CharField(max_length=20)),
                ('CampusFile', models.FileField(upload_to='')),
            ],
        ),
    ]
