# Generated by Django 5.0.6 on 2024-05-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jossacollegedata',
            name='CampusFile',
        ),
        migrations.AddField(
            model_name='jossacollegebranchdata',
            name='BranchAveragePackage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jossacollegebranchdata',
            name='BranchHeighestPackage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jossacollegebranchdata',
            name='BranchMedianPackage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jossacollegedata',
            name='CampusFile1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jossacollegedata',
            name='CampusFile2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jossacollegedata',
            name='CampusFile3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jossacollegedata',
            name='CollegeWebsite',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jossacollegedata',
            name='MedianPackage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jossacollegedata',
            name='NirfRank',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jossacollegedata',
            name='TotalPlaced',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jossacollegedata',
            name='TotalSat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jossacollegedata',
            name='TotalStudent',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jossacollegedata',
            name='AveragePackage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jossacollegedata',
            name='CollegeDescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jossacollegedata',
            name='HeighestPackage',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
